---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-prometheus-adapter
  namespace: monitoring
  labels:
    app: prometheus-adapter
data:
  config.yaml: |
    rules:
    - seriesQuery: 'nginx_ingress_controller_nginx_process_requests_total{controller_namespace!="",controller_pod!=""}' 
      resources:
        overrides:
          controller_namespace: {resource: "namespace"}
          controller_pod: {resource: "pod"}
      name:
        matches: ""
        as: "nginx_ingress_controller_nginx_process_requests_total" 
      metricsQuery: round(sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>), 0.001)
